import { Chat } from './features/chats';
import { SearchUser, User } from './features/users';

export const user: User = {
    id: 1,
    firstName: 'Shogun',
    lastName: 'Raiden',
    isVerified: true,
    username: 'raiden.shogun',
    userRoleName: 'USER',
    avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1703235528/cqk0dmky4xzlhtccuhvt.jpg',
};

export const chats: Chat[] = [
    {
        user: {
            id: 1,
            firstName: 'Shogun',
            lastName: 'Raiden',
            isVerified: true,
            username: 'raiden.shogun',
            userRoleName: 'USER',
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1703235528/cqk0dmky4xzlhtccuhvt.jpg',
        },
        latestMessage: {
            content: 'Mock dataddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
            messageTypeID: 1,
        },
    },
    {
        user: {
            id: 2,
            firstName: 'Vi',
            lastName: 'Nguyễn Thi Hà',
            isVerified: true,
            username: 'vi.nguyenthiha   ',
            userRoleName: 'USER',
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1675503302/qr5zsxkqcgc9bhvgxge3.png',
        },
        latestMessage: { content: 'Mock datadddddddddddddddddddddddddddddddddd', messageTypeID: 1 },
    },
    {
        user: {
            id: 3,
            firstName: 'Shogun',
            lastName: 'Raiden',
            isVerified: true,
            username: 'raiden.shogun',
            userRoleName: 'USER',
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1703235528/cqk0dmky4xzlhtccuhvt.jpg',
        },
        latestMessage: { content: 'Mock data', messageTypeID: 1 },
    },
    {
        user: {
            id: 4,
            firstName: 'Shogun',
            lastName: 'Raiden',
            isVerified: true,
            username: 'raiden.shogun',
            userRoleName: 'USER',
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1703235528/cqk0dmky4xzlhtccuhvt.jpg',
        },
        latestMessage: { content: 'Mock data', messageTypeID: 1 },
    },
    {
        user: {
            id: 5,
            firstName: 'Shogun',
            lastName: 'Raiden',
            isVerified: true,
            username: 'raiden.shogun',
            userRoleName: 'USER',
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1703235528/cqk0dmky4xzlhtccuhvt.jpg',
        },
        latestMessage: { content: 'Mock data', messageTypeID: 1 },
    },
    {
        user: {
            id: 6,
            firstName: 'Shogun',
            lastName: 'Raiden',
            isVerified: true,
            username: 'raiden.shogun',
            userRoleName: 'USER',
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1703235528/cqk0dmky4xzlhtccuhvt.jpg',
        },
        latestMessage: { content: 'Mock data', messageTypeID: 1 },
    },
    {
        user: {
            id: 7,
            firstName: 'Shogun',
            lastName: 'Raiden',
            isVerified: true,
            username: 'raiden.shogun',
            userRoleName: 'USER',
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1703235528/cqk0dmky4xzlhtccuhvt.jpg',
        },
        latestMessage: { content: 'Mock data', messageTypeID: 1 },
    },
    {
        user: {
            id: 8,
            firstName: 'Shogun',
            lastName: 'Raiden',
            isVerified: true,
            username: 'raiden.shogun',
            userRoleName: 'USER',
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1703235528/cqk0dmky4xzlhtccuhvt.jpg',
        },
        latestMessage: { content: 'Mock data', messageTypeID: 1 },
    },
    {
        user: {
            id: 9,
            firstName: 'Shogun',
            lastName: 'Raiden',
            isVerified: true,
            username: 'raiden.shogun',
            userRoleName: 'USER',
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1703235528/cqk0dmky4xzlhtccuhvt.jpg',
        },
        latestMessage: { content: 'Mock data', messageTypeID: 1 },
    },
    {
        user: {
            id: 10,
            firstName: 'Shogun',
            lastName: 'Raiden',
            isVerified: true,
            username: 'raiden.shogun',
            userRoleName: 'USER',
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1703235528/cqk0dmky4xzlhtccuhvt.jpg',
        },
        latestMessage: { content: 'Mock data', messageTypeID: 1 },
    },
    {
        user: {
            id: 11,
            firstName: 'Shogun',
            lastName: 'Raiden',
            isVerified: true,
            username: 'raiden.shogun',
            userRoleName: 'USER',
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1703235528/cqk0dmky4xzlhtccuhvt.jpg',
        },
        latestMessage: { content: 'Mock data', messageTypeID: 1 },
    },
    {
        user: {
            id: 12,
            firstName: 'Shogun',
            lastName: 'Raiden',
            isVerified: true,
            username: 'raiden.shogun',
            userRoleName: 'USER',
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1703235528/cqk0dmky4xzlhtccuhvt.jpg',
        },
        latestMessage: { content: 'Mock data', messageTypeID: 1 },
    },
];

export const searchResults: SearchUser[] = [
    {
        user: {
            id: 1,
            firstName: 'Shogun',
            lastName: 'Raiden',
            isVerified: true,
            username: 'raiden.shogun',
            userRoleName: 'USER',
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1703235528/cqk0dmky4xzlhtccuhvt.jpg',
        },
        isSentAddFriendNotification: true,
    },
    {
        user: {
            id: 2,
            firstName: 'Vi',
            lastName: 'Nguyễn Thi Hà',
            isVerified: true,
            username: 'vi.nguyenthiha   ',
            userRoleName: 'USER',
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1675503302/qr5zsxkqcgc9bhvgxge3.png',
        },
        isSentAddFriendNotification: false,
    },
    {
        user: {
            id: 3,
            firstName: 'Shogun',
            lastName: 'Raiden',
            isVerified: true,
            username: 'raiden.shogun',
            userRoleName: 'USER',
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1703235528/cqk0dmky4xzlhtccuhvt.jpg',
        },
        isSentAddFriendNotification: true,
    },
    {
        user: {
            id: 4,
            firstName: 'Shogun',
            lastName: 'Raiden',
            isVerified: true,
            username: 'raiden.shogun',
            userRoleName: 'USER',
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1703235528/cqk0dmky4xzlhtccuhvt.jpg',
        },
        isSentAddFriendNotification: false,
    },
    {
        user: {
            id: 5,
            firstName: 'Shogun',
            lastName: 'Raiden',
            isVerified: true,
            username: 'raiden.shogun',
            userRoleName: 'USER',
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1703235528/cqk0dmky4xzlhtccuhvt.jpg',
        },
        isSentAddFriendNotification: true,
    },
    {
        user: {
            id: 6,
            firstName: 'Shogun',
            lastName: 'Raiden',
            isVerified: true,
            username: 'raiden.shogun',
            userRoleName: 'USER',
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1703235528/cqk0dmky4xzlhtccuhvt.jpg',
        },
        isSentAddFriendNotification: true,
    },
    {
        user: {
            id: 7,
            firstName: 'Shogun',
            lastName: 'Raiden',
            isVerified: true,
            username: 'raiden.shogun',
            userRoleName: 'USER',
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1703235528/cqk0dmky4xzlhtccuhvt.jpg',
        },
        isSentAddFriendNotification: true,
    },
    {
        user: {
            id: 8,
            firstName: 'Shogun',
            lastName: 'Raiden',
            isVerified: true,
            username: 'raiden.shogun',
            userRoleName: 'USER',
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1703235528/cqk0dmky4xzlhtccuhvt.jpg',
        },
        isSentAddFriendNotification: true,
    },
    {
        user: {
            id: 9,
            firstName: 'Shogun',
            lastName: 'Raiden',
            isVerified: true,
            username: 'raiden.shogun',
            userRoleName: 'USER',
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1703235528/cqk0dmky4xzlhtccuhvt.jpg',
        },
        isSentAddFriendNotification: true,
    },
    {
        user: {
            id: 10,
            firstName: 'Shogun',
            lastName: 'Raiden',
            isVerified: true,
            username: 'raiden.shogun',
            userRoleName: 'USER',
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1703235528/cqk0dmky4xzlhtccuhvt.jpg',
        },
        isSentAddFriendNotification: true,
    },
    {
        user: {
            id: 11,
            firstName: 'Shogun',
            lastName: 'Raiden',
            isVerified: true,
            username: 'raiden.shogun',
            userRoleName: 'USER',
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1703235528/cqk0dmky4xzlhtccuhvt.jpg',
        },
        isSentAddFriendNotification: true,
    },
    {
        user: {
            id: 12,
            firstName: 'Shogun',
            lastName: 'Raiden',
            isVerified: true,
            username: 'raiden.shogun',
            userRoleName: 'USER',
            avatar: 'https://res.cloudinary.com/dnwauajh9/image/upload/v1703235528/cqk0dmky4xzlhtccuhvt.jpg',
        },
        isSentAddFriendNotification: true,
    },
];
